# Generated by Django 3.2.4 on 2021-06-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('nascimento', models.DateField()),
                ('rg', models.CharField(max_length=25, null=True)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('celular', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=75, null=True)),
                ('endereco', models.CharField(max_length=75)),
                ('num', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=75)),
                ('complemento', models.CharField(max_length=75, null=True)),
            ],
        ),
    ]
